# Site settings
title: PellePilot
email: pelle@pellepilot.com
url: http://pellepilot.se
description: "PellePilot är en av Transportstyrelsen godkänd flygskola och erbjuder utbildning till privatflygcertifikat samt mörkerbehörighet. Vi har också tillstånd att bedriva utbildning i avancerad flygning."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#a58c64'

# Footer settings
footer: PellePilot

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/pellepilotab
  - title: facebook
    url: https://www.facebook.com/pellepilotAB
  - title: instagram
    url: https://www.instagram.com/pellepilotab


# Build settings
markdown: kramdown
permalink: pretty
